using System.Collections.Immutable;
using System.Linq;
using System.Text;
using SzivarClubManager.SourceGenerator.Targets.Factory;

namespace SzivarClubManager.SourceGenerator.Factories.Generation;

public static class FactoryProvider
{
    public static string FileName => "FactoryProvider.g.cs";

    public static string GenerateSource(ImmutableArray<Factory> factories, ImmutableArray<FakeFactory> fakeFactories)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine("using SzivarClubManager.Datasources.Database;");
        sb.AppendLine("using SzivarClubManager.Datasources.Database.Factories;");
        sb.AppendLine("using SzivarClubManager.Datasources.Fake.Factories;");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Datasources;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class FactoryProvider");
        sb.AppendLine("{");
        GenerateFactoriesMap(sb, factories);
        sb.AppendLine();
        GenerateFakeFactoriesMap(sb, fakeFactories);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateFactoriesMap(StringBuilder sb, ImmutableArray<Factory> factories)
    {
        const string dbConnVarName = "connection";

        sb.AppendLine($"    private static partial Dictionary<Type, IFactory> GetGeneratedFactoriesMap(DatabaseConnection {dbConnVarName})");
        sb.AppendLine("    {");

        if (factories.Length == 0)
        {
            sb.AppendLine("        // No factories found");
            sb.AppendLine("        return new Dictionary<Type, IFactory>();");
            return;
        }

        sb.AppendLine("        // Helper factories");
        foreach (var f in factories.Where(x => x.FactoryType is FactoryType.Helper).OrderBy(x => x.Name))
        {
            sb.AppendLine($"        {f.Name} {f.Name.ToLower()} = {f.InstanceCreation(dbConnVarName)};");
        }

        sb.AppendLine();
        sb.AppendLine("        // Page factories");
        foreach (var f in factories.Where(x => x.FactoryType is FactoryType.Page).OrderBy(x => x.Dependencies.Length).ThenBy(x => x.Name))
        {
            if (f.Dependencies.Length == 0)
            {
                sb.AppendLine($"        {f.Name} {f.Name.ToLower()} = {f.InstanceCreation(dbConnVarName)};");
            }
            else
            {
                sb.AppendLine($"        {f.Name} {f.Name.ToLower()} = {f.InstanceCreation(dbConnVarName, f.Dependencies.Select(x => x.Name.ToLower()))};");
            }
        }


        sb.AppendLine();
        sb.AppendLine("        return new Dictionary<Type, IFactory>()");
        sb.AppendLine("        {");
        foreach (var f in factories.OrderBy(x => x.Name))
        {
            sb.AppendLine($"            {{ typeof({f.ModelName}), {f.Name.ToLower()} }},");
        }

        sb.Remove(sb.Length - 2, 1);

        sb.AppendLine("        };");

        sb.AppendLine("    }");
    }

    private static void GenerateFakeFactoriesMap(StringBuilder sb, ImmutableArray<FakeFactory> fakeFactories)
    {
        sb.AppendLine("    private static partial Dictionary<Type, IFactory> GetGeneratedFakeFactoriesMap()");
        sb.AppendLine("    {");

        if (fakeFactories.Length == 0)
        {
            sb.AppendLine("        // No fake factories found");
            sb.AppendLine("        return new Dictionary<Type, IFactory>();");
            return;
        }

        sb.AppendLine("        // Helper factories");
        foreach (var f in fakeFactories.Where(x => x.FactoryType is FactoryType.Helper).OrderBy(x => x.Name))
        {
            sb.AppendLine($"        {f.Name} {f.Name.ToLower()} = {f.InstanceCreation()};");
        }

        sb.AppendLine();
        sb.AppendLine("        // Page factories");
        foreach (var f in fakeFactories.Where(x => x.FactoryType is FactoryType.Page).OrderBy(x => x.Dependencies.Length).ThenBy(x => x.Name))
        {
            if (f.Dependencies.Length == 0)
            {
                sb.AppendLine($"        {f.Name} {f.Name.ToLower()} = {f.InstanceCreation()};");
            }
            else
            {
                sb.AppendLine($"        {f.Name} {f.Name.ToLower()} = {f.InstanceCreation(f.Dependencies.Select(x => x.Name.ToLower()))};");
            }
        }


        sb.AppendLine();
        sb.AppendLine("        return new Dictionary<Type, IFactory>()");
        sb.AppendLine("        {");
        foreach (var f in fakeFactories.OrderBy(x => x.Name))
        {
            sb.AppendLine($"            {{ typeof({f.ModelName}), {f.Name.ToLower()} }},");
        }

        sb.Remove(sb.Length - 2, 1);

        sb.AppendLine("        };");

        sb.AppendLine("    }");
    }
}