using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SzivarClubManager.SourceGenerator.GenerationTarget;

namespace SzivarClubManager.SourceGenerator;

[Generator]
public class Generator : IIncrementalGenerator
{
    private const string GeneratedOutputNamespace = "SzivarClubManager.SourceGeneration.Generated";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                (ctx, _) => GetTarget(ctx)
            )
            .Where(t => t is not null)
            .Select((t, _) => t!);

        // Create Page ViewModels from Models
        context.RegisterSourceOutput(targetCandidates, (ctx, activity) =>
        {
            if (activity is not PageActivityModel pam) return;
            ctx.AddSource($"{pam.ViewModelType}.g.cs", pam.GenerateViewModelSource());
        });


        // Group and create activities for ActivityCollection
        var withCompilation = targetCandidates.Collect().Combine(context.CompilationProvider);
        context.RegisterSourceOutput(withCompilation, (ctx, tuple) =>
        {
            (var activities, Compilation? compilation) = tuple;

            var validActivities = activities
                // Replace Page Models to Page ViewModel
                .Select(x => x is PageActivityModel pam ? pam.ToPageActivity() : x)
                // Only keep Page activities whose IDataSource has all required methods
                .Where(x => x is not PageActivity pa || pa.DataSourceHasMethods(compilation))
                // .Where(x => x is PageActivity pa && pa.DataSourceHasMethods(compilation))
                // Only keep Activities, only for type safety
                .OfType<Activity>()
                .ToImmutableArray();

            ctx.AddSource("ActivityCollection.g.cs", GenerateActivityCollection(validActivities));
        });
    }

    private static ITarget? GetTarget(GeneratorSyntaxContext context)
    {
        var pageActivityModel = PageActivityModel.IsTarget(context);
        if (pageActivityModel is not null) return pageActivityModel;

        var pageActivity = PageActivity.IsTarget(context);
        if (pageActivity is not null) return pageActivity;

        var activity = Activity.IsTarget(context);
        if (activity is not null) return activity;

        return null;
    }

    private static string GenerateActivityCollection(ImmutableArray<Activity> activities)
    {
        StringBuilder sb = new();
        sb.AppendLine("//<auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SzivarClubManager.Datasources;");
        sb.AppendLine("using SzivarClubManager.ViewModels.Activities;");
        sb.AppendLine();
        sb.AppendLine($"namespace {GeneratedOutputNamespace};");
        sb.AppendLine();
        sb.AppendLine("public static class ActivityCollection");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyDictionary<string, ActivityViewModel> GetActivities(IDataSource dataSource) => new Dictionary<string, ActivityViewModel>");
        sb.AppendLine("    {");
        if (activities.Length == 0) sb.AppendLine("        // No activities found");
        foreach (var activity in activities.OrderBy(a => a.DisplayName))
        {
            sb.AppendLine($"        {{ \"{activity.DisplayName}\", {activity.InstanceCreation("dataSource")} }},");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}