using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using SzivarClubManager.SourceGenerator.Activities.Target;

namespace SzivarClubManager.SourceGenerator.Activities.Generation;

public static class ActivityCollection
{
    public static string FileName => "ActivityCollection.g.cs";

    public static string GenerateSource(IEnumerable<Activity> activities)
    {
        const string factoryProviderVariableName = "factoryProvider";

        var orderedActivities = activities
            .GroupBy(x => x.GetType().Name)
            .OrderByDescending(x => x.Key)
            .Select(x => x.OrderBy(a => a.Name))
            .SelectMany(x => x)
            .ToArray();

        var namespaces = orderedActivities
            .Select(x => x.ActivitySymbol.ContainingNamespace)
            .Distinct(SymbolEqualityComparer.Default)
            .Where(x => x is not null)
            .Select(x => x!.ToDisplayString());

        StringBuilder sb = new();
        sb.AppendLine("//<auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine("using SzivarClubManager.Datasources;");
        sb.AppendLine("using SzivarClubManager.ViewModels.Activities;");
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.SourceGeneration.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class ActivityCollection");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IReadOnlyDictionary<string, ActivityViewModel> GetActivities(FactoryProvider {factoryProviderVariableName}) => new Dictionary<string, ActivityViewModel>");
        sb.AppendLine("    {");

        foreach (var a in orderedActivities)
        {

            if (a is PageActivity pa)
            {
                sb.AppendLine($"        {{ \"{pa.ModelName}\", {pa.InstanceCreation(factoryProviderVariableName)} }},");
            }
            else
            {
                sb.AppendLine($"        {{ \"{a.DisplayName}\", {a.InstanceCreation()} }},");
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}