using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using SzivarClubManager.SourceGenerator.Generators.Changes.Target;
using SzivarClubManager.SourceGenerator.Generators.Factories.Target;

namespace SzivarClubManager.SourceGenerator.Generators.Changes.Generation;

public static class Changes
{
    public const string FileName = "Changes.g.cs";

    private const string Type = "global::System.Type";
    private const string Dictionary = $"global::System.Collections.Generic.Dictionary<{Type}, global::{StringReferences.DataChangesInterface}>";


    public static string GenerateSource(ImmutableArray<Model> models)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Datasources.Change;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Stores generated change-tracking state and helpers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class Changes");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Contains per-model-type change trackers.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    private static {Dictionary} _dataChanges = null!;");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Indicates whether the change tracker registry has already been initialized.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static bool _isInitialized = false;");
        sb.AppendLine();
        GenerateInitialize(sb, models);
        sb.AppendLine();
        GenerateGetDataChange(sb);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateInitialize(StringBuilder sb, IEnumerable<Model> models)
    {
        const string factoryProvider = $"global::{StringReferences.FactoryProvider}";

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Initializes change tracking for all models that have a supported factory.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"provider\">FactoryProvider used to resolve model factories.</param>");
        sb.AppendLine($"    public static void Initialize({factoryProvider} provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        if(_isInitialized) return;");
        sb.AppendLine("        _isInitialized = true;");
        sb.AppendLine();
        sb.AppendLine($"        _dataChanges = new {Dictionary}()");
        sb.AppendLine("        {");
        foreach (var group in models.Where(x => x.Factory is not null).OrderBy(x => x.Factory!.Type))
        {
            if (group.Factory is not { } factory) continue;

            string modelGlobalName = group.Symbol.GlobalName();

            sb.AppendLine($"            // {factory.Type.ToTypeName()}");

            if (factory.Type.HasFlag(FactoryType.Page) && factory.Type.HasFlag(FactoryType.Helper))
            {
                // doesn't matter if passed factory is page or helper, both is IModelFactory<T>
                sb.AppendLine($"            {{ typeof({modelGlobalName}), new {StringReferences.DataChanges}<{modelGlobalName}>(provider.GetPageFactory<{modelGlobalName}>()) }},");
            }
            else if (factory.Type.HasFlag(FactoryType.Page))
            {
                sb.AppendLine($"            {{ typeof({modelGlobalName}), new {StringReferences.DataChanges}<{modelGlobalName}>(provider.GetPageFactory<{modelGlobalName}>()) }},");
            }
            else if (factory.Type.HasFlag(FactoryType.Helper))
            {
                sb.AppendLine($"            {{ typeof({modelGlobalName}), new {StringReferences.DataChanges}<{modelGlobalName}>(provider.GetHelperFactory<{modelGlobalName}>()) }},");
            }

            sb.AppendLine();
        }

        sb.AppendLine("        };");

        sb.AppendLine("    }");
    }

    private static void GenerateGetDataChange(StringBuilder sb)
    {
        const string modelInterface = $"global::{StringReferences.ModelInterface}";

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the change tracker for the specified model type.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <typeparam name=\"T\">The model type.</typeparam>");
        sb.AppendLine($"    private static {StringReferences.DataChanges}<T> GetDataChange<T>() where T : class, {modelInterface}");
        sb.AppendLine("    {");
        sb.AppendLine($"        return ({StringReferences.DataChanges}<T>)_dataChanges[typeof(T)];");
        sb.AppendLine("    }");
    }
}