using System.Collections.Generic;
using System.Text;
using SzivarClubManager.SourceGenerator.Generators.Changes.Target;

namespace SzivarClubManager.SourceGenerator.Generators.Changes.Generation;

public static class ChangesActivityViewModel
{
    public const string FileName = "ChangesActivityViewModel.g.cs";

    public static string GenerateSource(IEnumerable<PageActivityViewModel> pageActivityViewModels)
    {
        const string dataChangeRow = "global::SzivarClubManager.ViewModels.Activities.Change.DataChangeRow";
        const string observableCollection = $"global::System.Collections.ObjectModel.ObservableCollection<{dataChangeRow}>";

        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        // sb.AppendLine("using System.Collections.ObjectModel;");
        // sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.ViewModels.Activities.Change;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class ChangesActivityViewModel");
        sb.AppendLine("{");
        sb.AppendLine($"    private static {observableCollection} GetDataChangeRows() => new {observableCollection}");
        sb.AppendLine("    {");
        foreach (var vm in pageActivityViewModels)
        {
            sb.AppendLine($"        new {dataChangeRow}<{vm.ModelSymbol.GlobalName()}>(),");
        }
        sb.Remove(sb.Length - 2, 1);

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}