using System.Collections.Immutable;
using System.Linq;
using System.Text;
using SzivarClubManager.SourceGenerator.Generators.Changes.Target;

namespace SzivarClubManager.SourceGenerator.Generators.Changes.Generation;

public static class ChangesActivityViewModel
{
    public const string FileName = "ChangesActivityViewModel.g.cs";

    public static string GenerateSource(ImmutableArray<Model> models)
    {
        const string observableCollection = $"global::System.Collections.ObjectModel.ObservableCollection<global::{StringReferences.DataChangeRow}>";

        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.ViewModels.Activities.Change;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class ChangesActivityViewModel");
        sb.AppendLine("{");
        sb.AppendLine($"    private static {observableCollection} GetDataChangeRows() => new {observableCollection}");
        sb.AppendLine("    {");
        foreach (var model in models.Where(x => x.IsValid))
        {
            sb.AppendLine($"        new global::{StringReferences.DataChangeRow}<{model.Symbol.GlobalName()}>(),");
        }
        sb.Remove(sb.Length - 2, 1);

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}