using System.Collections.Generic;
using System.Linq;
using System.Text;
using SzivarClubManager.SourceGenerator.Targets.Factory;

namespace SzivarClubManager.SourceGenerator.Generators.Changes.Generation;

public static class Changes
{
    public const string FileName = "Changes.g.cs";

    private const string Type = "global::System.Type";
    private const string DataChangesInterface = "global::SzivarClubManager.Datasources.Change.IDataChanges";
    private const string Dictionary = $"global::System.Collections.Generic.Dictionary<{Type}, {DataChangesInterface}>";
    private const string DataChanges = "global::SzivarClubManager.Datasources.Change.DataChanges";


    public static string GenerateSource(IEnumerable<ModelGroup> models)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Datasources.Change;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Stores generated change-tracking state and helpers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class Changes");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Contains per-model-type change trackers.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    private static {Dictionary} _dataChanges = null!;");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Indicates whether the change tracker registry has already been initialized.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static bool _isInitialized = false;");
        sb.AppendLine();
        GenerateInitialize(sb, models, "    ");
        sb.AppendLine();
        GenerateGetDataChange(sb, "    ");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateInitialize(StringBuilder sb, IEnumerable<ModelGroup> models, string indent = "")
    {
        const string factoryProvider = "global::SzivarClubManager.Datasources.Factory.FactoryProvider";

        sb.AppendLine(indent + "/// <summary>");
        sb.AppendLine(indent + "/// Initializes change tracking for all models that have a supported factory.");
        sb.AppendLine(indent + "/// </summary>");
        sb.AppendLine(indent + $"/// <param name=\"provider\"><see cref=\"{factoryProvider.Replace("global::", "")}\"/> used to resolve model factories.</param>");
        sb.AppendLine(indent + $"public static void Initialize({factoryProvider} provider)");
        sb.AppendLine(indent + "{");
        sb.AppendLine(indent + "    if(_isInitialized) return;");
        sb.AppendLine(indent + "    _isInitialized = true;");
        sb.AppendLine();
        sb.AppendLine(indent + $"    _dataChanges = new {Dictionary}()");
        sb.AppendLine(indent + "    {");
        foreach (var group in models.Where(x => x.Factory is not null).OrderBy(x => x.Factory!.FactoryType))
        {
            if (group.Factory is not { } factory) continue;

            string modelGlobalName = group.Model.ModelSymbol.GlobalName();

            sb.AppendLine($"            // {factory.FactoryType.ToTypeName()}");

            if (factory.FactoryType.HasFlag(FactoryType.Page) && factory.FactoryType.HasFlag(FactoryType.Helper))
            {
                // doesn't matter if passed factory is page or helper, both is IModelFactory<T>
                sb.AppendLine(indent + $"        {{ typeof({modelGlobalName}), new {DataChanges}<{modelGlobalName}>(provider.GetPageFactory<{modelGlobalName}>()) }},");
            }
            else if (factory.FactoryType.HasFlag(FactoryType.Page))
            {
                sb.AppendLine(indent + $"        {{ typeof({modelGlobalName}), new {DataChanges}<{modelGlobalName}>(provider.GetPageFactory<{modelGlobalName}>()) }},");
            }
            else if (factory.FactoryType.HasFlag(FactoryType.Helper))
            {
                sb.AppendLine(indent + $"        {{ typeof({modelGlobalName}), new {DataChanges}<{modelGlobalName}>(provider.GetHelperFactory<{modelGlobalName}>()) }},");
            }

            sb.AppendLine();
        }

        sb.AppendLine(indent + "    };");

        sb.AppendLine(indent + "}");
    }

    private static void GenerateGetDataChange(StringBuilder sb, string indent = "")
    {
        const string modelInterface = "global::SzivarClubManager.Models.IModel";

        sb.AppendLine(indent + "/// <summary>");
        sb.AppendLine(indent + "/// Gets the change tracker for the specified model type.");
        sb.AppendLine(indent + "/// </summary>");
        sb.AppendLine(indent + "/// <typeparam name=\"T\">The model type.</typeparam>");
        sb.AppendLine(indent + $"private static {DataChanges}<T> GetDataChange<T>() where T : class, {modelInterface}");
        sb.AppendLine(indent + "{");
        sb.AppendLine(indent + $"    return ({DataChanges}<T>)_dataChanges[typeof(T)];");
        sb.AppendLine(indent + "}");
    }
}