using System.Collections.Generic;
using System.Text;

namespace SzivarClubManager.SourceGenerator.Generators.Changes.Generation;

public static class ModelRowBackgroundConverter
{
    public const string FileName = "ModelRowBackgroundConverter.g.cs";

    public static string GenerateSource(IEnumerable<ModelGroup> models)
    {
        const string modelInterface = "global::SzivarClubManager.Models.IModel";
        const string valueConverterInterface = "global::Avalonia.Data.Converters.IValueConverter";
        const string brushInterface = "global::Avalonia.Media.IBrush";
        const string changes = "global::SzivarClubManager.Datasources.Change.Changes";

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Converters;");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class ModelRowBackgroundConverter : {valueConverterInterface}");
        sb.AppendLine("{");
        sb.AppendLine($"    private static partial {brushInterface}? GetBrush({modelInterface} model) => model switch {{");
        foreach (var model in models)
        {
            string varName = model.Model.Name.ToLower();
            sb.AppendLine($"        {model.Model.ModelSymbol.GlobalName()} {varName} => {changes}.IsDeleted({varName}) ? GetDeleteBrush() : {changes}.IsEdited({varName}) ? GetEditBrush() : null,");
        }

        sb.AppendLine("        _ => null");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }
}