using System.Collections.Immutable;
using System.Text;
using SzivarClubManager.SourceGenerator.Generators.Changes.Target;

namespace SzivarClubManager.SourceGenerator.Generators.Changes.Generation;

public static class ModelRowBackgroundConverter
{
    public const string FileName = "ModelRowBackgroundConverter.g.cs";

    public static string GenerateSource(ImmutableArray<Model> models)
    {
        const string valueConverterInterface = "global::Avalonia.Data.Converters.IValueConverter";
        const string brushInterface = "global::Avalonia.Media.IBrush";

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Converters;");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class ModelRowBackgroundConverter : {valueConverterInterface}");
        sb.AppendLine("{");
        sb.AppendLine($"    private static partial {brushInterface}? GetBrush(global::{StringReferences.ModelInterface} model) => model switch {{");
        foreach (var model in models)
        {
            string varName = model.Name.ToLower();
            sb.AppendLine(
                $"        {model.Symbol.GlobalName()} {varName} => {StringReferences.Changes}.IsDeleted({varName}) ? GetDeleteBrush() : {StringReferences.Changes}.IsEdited({varName}) ? GetEditBrush() : null,");
        }

        sb.AppendLine("        _ => null");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }
}