<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14.0</LangVersion>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.9"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.9"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.9"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.9">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Bogus" Version="35.6.5" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="DotNetEnv" Version="3.1.1"/>
        <PackageReference Include="NetTopologySuite" Version="2.6.0" />
        <PackageReference Include="Npgsql" Version="10.0.0"/>
        <PackageReference Include="Npgsql.NetTopologySuite" Version="10.0.0" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.9"/>
    </ItemGroup>

    <ItemGroup>
        <None Update=".env">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SzivarClubManager.SourceGenerator\SzivarClubManager.SourceGenerator\SzivarClubManager.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <Analyzer Include="..\SzivarClubManager.SourceGenerator\SzivarClubManager.SourceGenerator\bin\$(Configuration)\netstandard2.0\SzivarClubManager.SourceGenerator.dll"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Activities\Page\PageActivityView.axaml.cs">
        <DependentUpon>PageActivityView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Activities\Change\ChangesActivityView.axaml.cs">
        <DependentUpon>ChangeActivityView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
