using System.Collections.Generic;
using System.Linq;
using System.Text;
using SzivarClubManager.SourceGenerator.Generators.Factories.Target;

namespace SzivarClubManager.SourceGenerator.Generators.Factories.Generation;

public static class FactoryProvider
{
    public static string FileName => "FactoryProvider.g.cs";

    public static string GenerateSource(IEnumerable<Factory> factories)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Datasources.Factory;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated part of <see cref=\"FactoryProvider\"/> containing factory registrations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed partial class FactoryProvider");
        sb.AppendLine("{");
        GenerateFactoriesMap(sb, factories);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateFactoriesMap(StringBuilder sb, IEnumerable<Factory> factories)
    {
        const string type = "global::System.Type";
        const string factory = "global::SzivarClubManager.Datasources.Factory.IFactory";
        const string dictionary = $"global::System.Collections.Generic.Dictionary<{type}, {factory}>";
        const string databaseConnection = "global::SzivarClubManager.Datasources.Database.DatabaseConnection";

        const string dbConnVarName = "connection";

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Builds a map of model types to generated factory instances.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"connection\">Active database connection used to initialize factory instances.</param>");
        sb.AppendLine("    /// <returns>A dictionary that maps model types to factory instances.</returns>");
        sb.AppendLine($"    private static partial {dictionary} GetGeneratedFactoriesMap({databaseConnection} {dbConnVarName})");
        sb.AppendLine("    {");


        var correctOrderedFactories = factories
            .Where(x => x.IsValid && x.ModelSymbol is not null)
            .OrderBy(x => x.Dependencies.Length).ThenBy(x => x.Name)
            .ToArray();

        if (correctOrderedFactories.Length == 0)
        {
            sb.AppendLine("        // No factories found");
            sb.AppendLine($"        return new {dictionary}();");
            sb.AppendLine("    }");
            return;
        }

        sb.AppendLine("        // Unspecified factories");
        foreach (var f in correctOrderedFactories.Where(x => x.Type == FactoryType.Unspecified))
        {
            sb.AppendLine($"        {f.InstanceCreation(dbConnVarName)}");
        }

        sb.AppendLine();
        sb.AppendLine("        // Helper factories");
        foreach (var f in correctOrderedFactories.Where(x => x.Type == FactoryType.Helper))
        {
            sb.AppendLine($"        {f.InstanceCreation(dbConnVarName)}");
        }

        sb.AppendLine();
        sb.AppendLine("        // Page-Helper factories");
        foreach (var f in correctOrderedFactories.Where(x => (x.Type & (FactoryType.Page | FactoryType.Helper)) == (FactoryType.Page | FactoryType.Helper)))
        {
            sb.AppendLine($"        {f.InstanceCreation(dbConnVarName)}");
        }

        sb.AppendLine();
        sb.AppendLine("        // Page factories");
        foreach (var f in correctOrderedFactories.Where(x => x.Type == FactoryType.Page))
        {
            sb.AppendLine($"        {f.InstanceCreation(dbConnVarName)}");
        }


        sb.AppendLine();
        sb.AppendLine($"        return new {dictionary}()");
        sb.AppendLine("        {");
        foreach (var f in correctOrderedFactories.OrderBy(x => x.Name))
        {
            sb.AppendLine($"            {{ typeof({f.ModelSymbol!.GlobalName()}), {f.VariableName} }},");
        }

        sb.Remove(sb.Length - 2, 1);

        sb.AppendLine("        };");

        sb.AppendLine("    }");
    }
}