using System.Collections.Immutable;
using System.Linq;
using System.Text;
using SzivarClubManager.SourceGenerator.CommonTargets.Factory;

namespace SzivarClubManager.SourceGenerator.Generators.Factories.Generation;

public static class FactoryProvider
{
    public static string FileName => "FactoryProvider.g.cs";

    public static string GenerateSource(ImmutableArray<Factory> factories)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Datasources;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class FactoryProvider");
        sb.AppendLine("{");
        GenerateFactoriesMap(sb, factories);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateFactoriesMap(StringBuilder sb, ImmutableArray<Factory> factories)
    {
        const string type = "global::System.Type";
        const string factory = "global::SzivarClubManager.Datasources.IFactory";
        const string dictionary = $"global::System.Collections.Generic.Dictionary<{type}, {factory}>";
        const string databaseConnection = "global::SzivarClubManager.Datasources.Database.DatabaseConnection";

        const string dbConnVarName = "connection";

        sb.AppendLine($"    private static partial {dictionary} GetGeneratedFactoriesMap({databaseConnection} {dbConnVarName})");
        sb.AppendLine("    {");

        if (factories.Length == 0)
        {
            sb.AppendLine("        // No factories found");
            sb.AppendLine($"        return new {dictionary}();");
            return;
        }

        sb.AppendLine("        // Helper factories");
        foreach (var f in factories.Where(x => x.FactoryType == FactoryType.Helper).OrderBy(x => x.Name))
        {
            sb.AppendLine($"        {f.VariableDeclaration(dbConnVarName)}");
        }

        sb.AppendLine();
        sb.AppendLine("        // Page-Helper factories");
        foreach (var f in factories.Where(x => (x.FactoryType & (FactoryType.Page | FactoryType.Helper)) == (FactoryType.Page | FactoryType.Helper)).OrderBy(x => x.Name))
        {
            sb.AppendLine($"        {f.VariableDeclaration(dbConnVarName)}");
        }

        sb.AppendLine();
        sb.AppendLine("        // Page factories");
        foreach (var f in factories.Where(x => x.FactoryType == FactoryType.Page).OrderBy(x => x.Dependencies.Length).ThenBy(x => x.Name))
        {
            if (f.Dependencies.Length == 0)
            {
                sb.AppendLine($"        {f.VariableDeclaration(dbConnVarName)}");
            }
            else
            {
                sb.AppendLine($"        {f.VariableDeclaration(dbConnVarName, f.Dependencies.Select(x => x.PascalCaseName()))}");
            }
        }


        sb.AppendLine();
        sb.AppendLine($"        return new {dictionary}()");
        sb.AppendLine("        {");
        foreach (var f in factories.OrderBy(x => x.Name))
        {
            sb.AppendLine($"            {{ typeof({f.ModelSymbol.GlobalName()}), {f.FactorySymbol.PascalCaseName()} }},");
        }

        sb.Remove(sb.Length - 2, 1);

        sb.AppendLine("        };");

        sb.AppendLine("    }");
    }
}