using System.Collections.Generic;
using System.Text;
using SzivarClubManager.SourceGenerator.Targets;
using SzivarClubManager.SourceGenerator.Targets.Factory;
using SzivarClubManager.SourceGenerator.Types;

namespace SzivarClubManager.SourceGenerator.Changes.Generation;

public static class Changes
{
    public static string FileName => "Changes.g.cs";

    public static string GenerateSource(IEnumerable<ModelGroup> models)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine("using SzivarClubManager.Models.Editable;");
        sb.AppendLine("using SzivarClubManager.Datasources;");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Datasources.Change;");
        sb.AppendLine();
        sb.AppendLine("public static partial class Changes");
        sb.AppendLine("{");
        sb.AppendLine("    private static Dictionary<Type, IDataChanges> _dataChanges = null!;");
        sb.AppendLine("    private static bool _isInitialized = false;");
        sb.AppendLine();
        GenerateInitialize(sb, models, "    ");
        sb.AppendLine();
        GenerateGetDataChange(sb, "    ");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateInitialize(StringBuilder sb, IEnumerable<ModelGroup> models, string indent = "")
    {
        sb.AppendLine(indent + "public static void Initialize(FactoryProvider provider)");
        sb.AppendLine(indent + "{");
        sb.AppendLine(indent + "    if(_isInitialized) return;");
        sb.AppendLine(indent + "    _isInitialized = true;");
        sb.AppendLine();

        sb.AppendLine(indent + "    _dataChanges = new Dictionary<Type, IDataChanges>()");
        sb.AppendLine(indent + "    {");
        foreach (var group in models)
        {
            if (group.Factory is not { } factory) continue;

            if (factory.FactoryType.HasFlag(FactoryType.Page) && factory.FactoryType.HasFlag(FactoryType.Helper))
            {
                // doesn't matter if passed factory is page or helper, both is IModelFactory<T>
                sb.Append(indent + $"        {{ typeof({group.Model.Name}), new DataChanges<{group.Model.Name}>(provider.GetPageFactory<{group.Model.Name}>()) }},");
            }
            else if (factory.FactoryType.HasFlag(FactoryType.Page))
            {
                sb.Append(indent + $"        {{ typeof({group.Model.Name}), new DataChanges<{group.Model.Name}>(provider.GetPageFactory<{group.Model.Name}>()) }},");
            }
            else if (factory.FactoryType.HasFlag(FactoryType.Helper))
            {
                sb.Append(indent + $"        {{ typeof({group.Model.Name}), new DataChanges<{group.Model.Name}>(provider.GetHelperFactory<{group.Model.Name}>()) }},");
            }

            sb.AppendLine($" // {factory.FactoryType.ToTypeName()}");
        }

        sb.AppendLine(indent + "    };");

        sb.AppendLine(indent + "}");
    }

    private static void GenerateGetDataChange(StringBuilder sb, string indent = "")
    {
        sb.AppendLine(indent + "private static DataChanges<T> GetDataChange<T>() where T : class, IModel");
        sb.AppendLine(indent + "{");
        sb.AppendLine(indent + "    return (DataChanges<T>)_dataChanges[typeof(T)];");
        sb.AppendLine(indent + "}");
    }
}