using System.Collections.Generic;
using System.Text;
using SzivarClubManager.SourceGenerator.Changes.Target;

namespace SzivarClubManager.SourceGenerator.Changes.Generation;

public static class ChangesActivityViewModel
{
    public static string FileName => "ChangesActivityViewModel.g.cs";

    public static string GenerateSource(IEnumerable<PageActivityViewModel> pageActivityViewModels)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.ObjectModel;");
        sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.ViewModels.Activities.Change;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class ChangesActivityViewModel");
        sb.AppendLine("{");
        sb.AppendLine("    private static ObservableCollection<DataChangeRow> GetDataChangeRows() => new ObservableCollection<DataChangeRow>");
        sb.AppendLine("    {");
        foreach (var vm in pageActivityViewModels)
        {
            sb.AppendLine($"        new DataChangeRow<{vm.ModelName}>(),");
        }
        sb.Remove(sb.Length - 2, 1);

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}