using System.Collections.Generic;
using System.Text;
using SzivarClubManager.SourceGenerator.Targets;
using SzivarClubManager.SourceGenerator.Types;

namespace SzivarClubManager.SourceGenerator.Changes.Generation;

public static class ModelRowBackgroundConverter
{
    public static string FileName => "ModelRowBackgroundConverter.g.cs";

    public static string GenerateSource(IEnumerable<ModelGroup> models)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Avalonia.Media;");
        sb.AppendLine("using Avalonia.Data.Converters;");
        sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine("using SzivarClubManager.Datasources.Change;");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Converters;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class ModelRowBackgroundConverter : IValueConverter");
        sb.AppendLine("{");
        sb.AppendLine("    private static partial IBrush? GetBrush(IModel model) => model switch {");
        foreach (var model in models)
        {
            sb.AppendLine(
                $"        {model.Model.Name} {model.Model.Name.ToLower()} => Changes.IsDeleted({model.Model.Name.ToLower()}) ? GetDeleteBrush() : Changes.IsEdited({model.Model.Name.ToLower()}) ? GetEditBrush() : null,");
        }

        sb.AppendLine("        _ => null");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }
}