using System.Text;
using SzivarClubManager.SourceGenerator.Generators.Filters.Target;
using SzivarClubManager.SourceGenerator.Generators.FilterViewModels.Target;

namespace SzivarClubManager.SourceGenerator.Generators.FilterViewModels.Generation;

public static class ModelFilterViewModel
{
    private const string FieldState = "global::SzivarClubManager.ViewModels.Activities.Page.Filter.FieldState";

    public static string GetFileName(FilterViewModel vm) => $"{vm.ViewModelSymbol.Name}.g.cs";

    public static string GenerateSource(FilterViewModel vm, FilterModel filter)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine($"namespace {vm.ViewModelSymbol.ContainingNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public {(vm.ViewModelSymbol.IsSealed ? "sealed " : "")}partial class {vm.ViewModelSymbol.Name}");
        sb.AppendLine("{");
        // GenerateFilterProperty(sb, filter);
        // sb.AppendLine();
        // sb.AppendLine();
        GenerateTextProperties(sb, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateStateProperties(sb, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateCanClearProperties(sb, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateCanApplyProperty(sb, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateClearCommandProperties(sb, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateApplyCommandProperty(sb);
        sb.AppendLine();
        sb.AppendLine();
        GenerateClearCommandMethods(sb, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateCheckStateMethods(sb, vm, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateOnChangedMethods(sb, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateApplyCommandMethod(sb, filter);
        sb.AppendLine();
        sb.AppendLine();
        GenerateRefreshFilterFieldsMethod(sb, filter);
        sb.Append("}");


        return sb.ToString();
    }

    private static void GenerateFilterProperty(StringBuilder sb, FilterModel filter)
    {
        sb.AppendLine($"    public override {filter.FilterType.GlobalName()} Filter");
        sb.AppendLine("    {");
        sb.AppendLine("        get;");
        sb.AppendLine("        init");
        sb.AppendLine("        {");
        sb.AppendLine("            field = value;");
        sb.AppendLine("            RefreshFilterFields();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void GenerateTextProperties(StringBuilder sb, FilterModel filter)
    {
        foreach (var prop in filter.Properties)
        {
            sb.AppendLine($"    public string {prop.Name}Text");
            sb.AppendLine("    {");
            sb.AppendLine("        get;");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine("            SetProperty(ref field, value);");
            sb.AppendLine($"            On{prop.Name}TextChanged();");
            sb.AppendLine("        }");
            sb.AppendLine("    } = string.Empty;");
            sb.AppendLine();
        }

        sb.Remove(sb.Length - 1, 1);
    }

    private static void GenerateStateProperties(StringBuilder sb, FilterModel filter)
    {
        foreach (var prop in filter.Properties)
        {
            sb.AppendLine($"    public {FieldState} {prop.Name}State");
            sb.AppendLine("    {");
            sb.AppendLine("        get;");
            sb.AppendLine("        set => SetProperty(ref field, value);");
            sb.AppendLine($"    }} = {FieldState}.None;");
            sb.AppendLine();
        }

        sb.Remove(sb.Length - 1, 1);
    }

    private static void GenerateCanClearProperties(StringBuilder sb, FilterModel filter)
    {
        foreach (var pair in filter.PropertyGroups)
        {
            if (pair.Value.Length == 1)
            {
                sb.AppendLine($"    private bool CanClear{pair.Value[0].Name}Text => !string.IsNullOrWhiteSpace({pair.Value[0].Name}Text);");
            }
            else
            {
                sb.Append($"    private bool CanClear{pair.Key}Text => !string.IsNullOrWhiteSpace({pair.Value[0].Name}Text)")
                    .AppendLine($" || !string.IsNullOrWhiteSpace({pair.Value[1].Name}Text);");
            }
        }
    }

    private static void GenerateCanApplyProperty(StringBuilder sb, FilterModel filter)
    {
        sb.Append("    private bool CanApply => ");

        bool anyBefore = false;

        foreach (var prop in filter.Properties)
        {
            if (!anyBefore) anyBefore = true;
            else sb.Append("                             ");

            sb.AppendLine($"{prop.Name}State is not {FieldState}.Invalid &&");
        }

        sb.Remove(sb.Length - 5, 5); // " &&\n";
        sb.AppendLine(";");
    }

    private static void GenerateOnChangedMethods(StringBuilder sb, FilterModel filter)
    {
        foreach (var pair in filter.PropertyGroups)
        {
            foreach (var prop in pair.Value)
            {
                sb.AppendLine($"    private void On{prop.Name}TextChanged()");
                sb.AppendLine("    {");
                sb.AppendLine($"        Clear{pair.Key}TextCommand.NotifyCanExecuteChanged();");
                sb.AppendLine($"        ApplyCommand.NotifyCanExecuteChanged();");
                sb.AppendLine($"        Check{prop.Name}State();");
                sb.AppendLine("    }");
            }
        }
    }

    private static void GenerateClearCommandProperties(StringBuilder sb, FilterModel filter)
    {
        const string relayCommandInterface = "global::CommunityToolkit.Mvvm.Input.IRelayCommand";
        const string relayCommand = "global::CommunityToolkit.Mvvm.Input.RelayCommand";
        const string action = "global::System.Action";

        foreach (var pair in filter.PropertyGroups)
        {
            sb.AppendLine($"    public {relayCommandInterface} Clear{pair.Key}TextCommand => field ??= new {relayCommand}(new {action}(Clear{pair.Key}Text), () => CanClear{pair.Key}Text);");
        }
    }

    private static void GenerateClearCommandMethods(StringBuilder sb, FilterModel filter)
    {
        foreach (var pair in filter.PropertyGroups)
        {
            if (pair.Value.Length == 1)
            {
                sb.AppendLine($"    private void Clear{pair.Value[0].Name}Text() => {pair.Value[0].Name}Text = string.Empty;");
            }
            else
            {
                sb.AppendLine($"    private void Clear{pair.Key}Text() => {pair.Value[0].Name}Text = {pair.Value[1].Name}Text = string.Empty;");
            }
        }
    }

    private static void GenerateCheckStateMethods(StringBuilder sb, FilterViewModel vm, FilterModel filter)
    {
        const string defaultPredicate = "x => false";
        foreach (var prop in filter.Properties)
        {
            switch (prop.Type)
            {
                case PropertyTypes.String:
                    sb.AppendLine(
                        $"    private void Check{prop.Name}State() => {prop.Name}State = {FieldState}.CheckOptionalStringField({prop.Name}Text, {vm.TryGetMethodName(prop) ?? defaultPredicate});");
                    break;
                case PropertyTypes.Int:
                    sb.AppendLine(
                        $"    private void Check{prop.Name}State() => {prop.Name}State = {FieldState}.CheckOptionalIntField({prop.Name}Text, {vm.TryGetMethodName(prop) ?? defaultPredicate});");
                    break;
                case PropertyTypes.Double:
                    sb.AppendLine(
                        $"    private void Check{prop.Name}State() => {prop.Name}State = {FieldState}.CheckOptionalDoubleField({prop.Name}Text, {vm.TryGetMethodName(prop) ?? defaultPredicate});");
                    break;
            }
        }
    }

    private static void GenerateApplyCommandProperty(StringBuilder sb)
    {
        sb.AppendLine("    public global::CommunityToolkit.Mvvm.Input.IRelayCommand ApplyCommand => field ??= new global::CommunityToolkit.Mvvm.Input.RelayCommand(Apply, () => CanApply);");
    }

    private static void GenerateApplyCommandMethod(StringBuilder sb, FilterModel filter)
    {
        sb.AppendLine("    private void Apply()");
        sb.AppendLine("    {");
        foreach (var prop in filter.Properties)
        {
            switch (prop.Type)
            {
                case PropertyTypes.String:
                    sb.AppendLine($"        if ({prop.Name}State is {FieldState}.Valid) Filter.{prop.Name} = {prop.Name}Text;");
                    break;
                case PropertyTypes.Int:
                    sb.AppendLine($"        if ({prop.Name}State is {FieldState}.Valid) Filter.{prop.Name} = int.Parse({prop.Name}Text);");
                    break;
                case PropertyTypes.Double:
                    sb.AppendLine($"        if ({prop.Name}State is {FieldState}.Valid) Filter.{prop.Name} = double.Parse({prop.Name}Text);");
                    break;
            }
        }

        sb.AppendLine();
        sb.AppendLine("        PopupService.ClosePopup();");
        sb.AppendLine("        AfterApplyCommand.Execute(null);");

        sb.AppendLine("    }");
    }

    private static void GenerateRefreshFilterFieldsMethod(StringBuilder sb, FilterModel filter)
    {
        sb.AppendLine("    public override void RefreshFilterFields()");
        sb.AppendLine("    {");
        foreach (var prop in filter.Properties)
        {
            switch (prop.Type)
            {
                case PropertyTypes.String:
                    sb.AppendLine($"        {prop.Name}Text = Filter.{prop.Name} ?? string.Empty;");
                    break;
                case PropertyTypes.Int:
                    sb.AppendLine($"        {prop.Name}Text = Filter.{prop.Name}?.ToString() ?? string.Empty;");
                    break;
                case PropertyTypes.Double:
                    sb.AppendLine($"        {prop.Name}Text = Filter.{prop.Name}?.ToString(\"0.00000\") ?? string.Empty;");
                    break;
            }
        }

        sb.AppendLine("    }");
    }
}