create table public.spatial_ref_sys
(
    srid      integer not null
        primary key
        constraint spatial_ref_sys_srid_check
            check ((srid > 0) AND (srid <= 998999)),
    auth_name varchar(256),
    auth_srid integer,
    srtext    varchar(2048),
    proj4text varchar(2048)
);

alter table public.spatial_ref_sys
    owner to postgres;

grant select on public.spatial_ref_sys to public;

create table public.shops
(
    id         integer generated by default as identity
        primary key,
    name       varchar,
    address    text,
    city       varchar,
    created_at timestamp,
    updated_at timestamp,
    location   geometry(Point, 4326)
);

comment on table public.shops is 'Dohányboltok adatai országos szinten. GPS koordinátákkal és opcionális nyitvatartással.';

alter table public.shops
    owner to develop;

create table public.cigar_brands
(
    id   integer generated by default as identity
        primary key,
    name varchar
        unique
);

comment on table public.cigar_brands is 'Szivar márkák listája (pl. Cohiba, Montecristo). Későbbi szűréshez.';

alter table public.cigar_brands
    owner to develop;

create table public.cigars
(
    id       integer generated by default as identity
        primary key,
    name     varchar,
    brand_id integer
        references public.cigar_brands
);

comment on table public.cigars is 'Később hozzzákell még adni attríbutumokat, pl mekkora, ilyesmi';

alter table public.cigars
    owner to develop;

create table public.days_of_week
(
    id  integer generated by default as identity
        constraint days_of_week_pk
        primary key,
    day varchar(9) not null
);

alter table public.days_of_week
    owner to develop;

create table public.shop_opening_hours
(
    id         serial
        primary key,
    shop_id    integer
        references public.shops,
    day_id     integer
        constraint shop_opening_hours_days_of_week_id_fk
            references public.days_of_week,
    open_hour  time,
    close_hour time
);

comment on table public.shop_opening_hours is 'Nyitvatartás tárolás';

alter table public.shop_opening_hours
    owner to develop;

create table public.roles
(
    id   integer generated always as identity
        constraint roles_pk
        primary key,
    name varchar(15)
);

alter table public.roles
    owner to develop;

create table public.users
(
    id            integer generated by default as identity
        primary key,
    name          varchar,
    email         varchar
        unique,
    password_hash varchar(255),
    role_id       integer
        constraint users_roles_id_fk
            references public.roles,
    created_at    timestamp default now()
);

comment on table public.users is 'Felhasználók táblája. Tárolja a bejelentkezési adatokat és a szerepkört (user/admin).';

alter table public.users
    owner to develop;

create table public.cigar_availability
(
    id         integer generated by default as identity
        primary key,
    shop_id    integer
        references public.shops,
    user_id    integer
        references public.users,
    confirmed  boolean,
    created_at timestamp
);

comment on table public.cigar_availability is 'Közösségi jelölés: egy boltban elérhető szivar. Admin később megerősítheti (confirmed).';

alter table public.cigar_availability
    owner to develop;

create table public.user_actions
(
    id          integer generated by default as identity
        primary key,
    user_id     integer
        references public.users,
    shop_id     integer
        references public.shops,
    action_type varchar,
    note        text,
    created_at  timestamp
);

comment on table public.user_actions is 'Felhasználói aktivitások (pl. itt vettem szivart, új bolt jelölése).';

alter table public.user_actions
    owner to develop;

create table public.shop_photos
(
    id          integer generated by default as identity
        primary key,
    shop_id     integer
        references public.shops,
    user_id     integer
        references public.users,
    photo_url   text,
    uploaded_at timestamp
);

comment on table public.shop_photos is 'Boltokhoz feltöltött fotók. A közösség tölti fel, admin ellenőrizheti.';

alter table public.shop_photos
    owner to develop;

create table public.reviews
(
    id         integer generated by default as identity
        primary key,
    shop_id    integer
        references public.shops,
    user_id    integer
        references public.users,
    rating     integer,
    comment    text,
    created_at timestamp
);

comment on table public.reviews is 'Értékelések és kommentek. 1–5 csillag közötti értékelés, szöveges megjegyzéssel.';

alter table public.reviews
    owner to develop;

create table public.shop_cigar_brands
(
    id         integer generated by default as identity
        primary key,
    shop_id    integer
        references public.shops,
    cigar_id   integer
        references public.cigars,
    added_by   integer
        references public.users,
    created_at timestamp
);

comment on table public.shop_cigar_brands is 'Kapcsolótábla boltok és márkák között. Közösségi bővítés lehetséges.';

alter table public.shop_cigar_brands
    owner to develop;

create table public.db_tables
(
    id   integer generated by default as identity (minvalue 0)
        constraint db_tables_pk
        primary key,
    name varchar(25) not null
);

alter table public.db_tables
    owner to develop;

create table public.db_columns
(
    id       integer generated by default as identity (minvalue 0)
        constraint db_columns_pk
        primary key,
    table_id integer     not null
        constraint db_columns_db_tables_fk
            references public.db_tables,
    name     varchar(25) not null
);

alter table public.db_columns
    owner to develop;

create table public.suggestion_user_rating
(
    id      integer generated by default as identity (minvalue 0)
        constraint validation_rating_by_user_pk
        primary key,
    "like"  boolean not null,
    user_id integer not null
        constraint validation_rating_user_fk
            references public.users
);

alter table public.suggestion_user_rating
    owner to develop;

create table public.suggestion_type
(
    id   integer generated always as identity
        constraint suggestion_type_pk
        primary key,
    type varchar(50) not null
);

alter table public.suggestion_type
    owner to develop;

create table public.suggestion
(
    id         integer generated by default as identity (minvalue 0)
        constraint validation_pk
        primary key,
    column_id  integer
        constraint validation_db_columns_fk
            references public.db_columns,
    record_id  integer,
    new_value  text not null,
    user_id    integer default 0
        constraint validation_user_id_fk
            references public.users,
    created_at date    default now(),
    type_id    integer
        constraint suggestion_suggestion_type_id_fk
            references public.suggestion_type
);

comment on column public.suggestion.record_id is 'Átirandó rekord id-je, null ha teljesen új adat';

comment on column public.suggestion.user_id is 'Kezdeményező felhasználó';

alter table public.suggestion
    owner to develop;

create table public.suggestion_ratings
(
    id             integer generated by default as identity (minvalue 0)
        constraint validation_ratings_pk
        primary key,
    suggestion_id  integer not null
        constraint validation_ratings_suggestion_fk
            references public.suggestion,
    user_rating_id integer not null
        constraint validation_ratings_user_rating_fk
            references public.suggestion_user_rating
);

alter table public.suggestion_ratings
    owner to develop;

