CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password_hash" text,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "shops" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "address" text,
  "city" varchar,
  "latitude" decimal,
  "longitude" decimal,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cigar_availability" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shop_id" int,
  "user_id" int,
  "confirmed" boolean,
  "created_at" timestamp
);

CREATE TABLE "user_actions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "shop_id" int,
  "action_type" varchar,
  "note" text,
  "created_at" timestamp
);

CREATE TABLE "shop_photos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shop_id" int,
  "user_id" int,
  "photo_url" text,
  "uploaded_at" timestamp
);

CREATE TABLE "cigar_brands" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "shop_cigar_brands" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shop_id" int,
  "cigar_id" int,
  "added_by" int,
  "created_at" timestamp
);

CREATE TABLE "reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shop_id" int,
  "user_id" int,
  "rating" int,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "cigars" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "brand_id" int
);

CREATE TABLE "shop_opening_hours" (
  "id" SERIAL PRIMARY KEY,
  "shop_id" int,
  "days_of_week" varchar,
  "open_hour" time,
  "close_hour" time
);

COMMENT ON TABLE "users" IS 'Felhasználók táblája. Tárolja a bejelentkezési adatokat és a szerepkört (user/admin).';

COMMENT ON TABLE "shops" IS 'Dohányboltok adatai országos szinten. GPS koordinátákkal és opcionális nyitvatartással.';

COMMENT ON TABLE "cigar_availability" IS 'Közösségi jelölés: egy boltban elérhető szivar. Admin később megerősítheti (confirmed).';

COMMENT ON TABLE "user_actions" IS 'Felhasználói aktivitások (pl. itt vettem szivart, új bolt jelölése).';

COMMENT ON TABLE "shop_photos" IS 'Boltokhoz feltöltött fotók. A közösség tölti fel, admin ellenőrizheti.';

COMMENT ON TABLE "cigar_brands" IS 'Szivar márkák listája (pl. Cohiba, Montecristo). Későbbi szűréshez.';

COMMENT ON TABLE "shop_cigar_brands" IS 'Kapcsolótábla boltok és márkák között. Közösségi bővítés lehetséges.';

COMMENT ON TABLE "reviews" IS 'Értékelések és kommentek. 1–5 csillag közötti értékelés, szöveges megjegyzéssel.';

COMMENT ON TABLE "cigars" IS 'Később hozzzákell még adni attríbutumokat, pl mekkora, ilyesmi';

COMMENT ON TABLE "shop_opening_hours" IS 'nyitvatartás tárolás';

ALTER TABLE "cigar_availability" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "cigar_availability" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_actions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_actions" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "shop_photos" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "shop_photos" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "shop_cigar_brands" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "shop_cigar_brands" ADD FOREIGN KEY ("cigar_id") REFERENCES "cigars" ("id");

ALTER TABLE "shop_cigar_brands" ADD FOREIGN KEY ("added_by") REFERENCES "users" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cigars" ADD FOREIGN KEY ("brand_id") REFERENCES "cigar_brands" ("id");

ALTER TABLE "shop_opening_hours" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");
