using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SzivarClubManager.SourceGenerator.Factories.Target;

namespace SzivarClubManager.SourceGenerator.Factories;

[Generator]
public class Generator : IIncrementalGenerator
{
    //TODO : warn on type collision
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                (ctx, _) => GetTarget(ctx)
            )
            .Where(t => t is not null)
            .Select((t, _) => t!);

        ;


        context.RegisterSourceOutput(targetCandidates.Collect(), (ctx, factories) =>
        {
            ctx.AddSource(
                "FactoryProvider.g.cs",
                GenerateFactoryCollection(factories)
            );
        });
    }

    private static Factory? GetTarget(GeneratorSyntaxContext context)
    {
        const string factoryOfAttribute = "SzivarClubManager.SourceGeneration.FactoryOfAttribute";
        const string mockFactoryOfAttribute = "SzivarClubManager.SourceGeneration.MockFactoryOfAttribute";

        if (context.SemanticModel.GetDeclaredSymbol((TypeDeclarationSyntax)context.Node) is not INamedTypeSymbol typeSymbol) return null;
        var factoryAttributeSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName(factoryOfAttribute);
        var mockFactoryAttributeSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName(mockFactoryOfAttribute);
        if (factoryAttributeSymbol is null || mockFactoryAttributeSymbol is null) return null;

        foreach (var attribute in typeSymbol.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, factoryAttributeSymbol) &&
                !SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, mockFactoryAttributeSymbol))
            {
                continue;
            }

            if (
                attribute.ConstructorArguments.Length == 1 &&
                attribute.ConstructorArguments[0] is { Value: INamedTypeSymbol mockModelTypeSymbol }
            )
            {
                return new MockFactory(
                    new TypeName(typeSymbol.Name, typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)),
                    new TypeName(mockModelTypeSymbol.Name, mockModelTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                );
            }
            if (
                attribute.ConstructorArguments.Length == 2 &&
                attribute.ConstructorArguments[0] is { Value: INamedTypeSymbol modelTypeSymbol } &&
                attribute.ConstructorArguments[1].Value is bool databaseRequired
            )
            {
                return new Factory(
                    new TypeName(typeSymbol.Name, typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)),
                    new TypeName(modelTypeSymbol.Name, modelTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)),
                    databaseRequired
                );
            }
        }

        return null;
    }

    private static string GenerateFactoryCollection(ImmutableArray<Factory> factories)
    {
        const string databaseConnectionVariableName = "connection";
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine("using SzivarClubManager.Datasources.Database;");
        sb.AppendLine("using SzivarClubManager.Datasources.Database.Factories;");
        sb.AppendLine("using SzivarClubManager.Datasources.Mock.Factories;");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Datasources;");
        sb.AppendLine();
        sb.AppendLine("public partial class FactoryProvider");
        sb.AppendLine("{");
        // normal
        sb.AppendLine(
            $"    private static partial Dictionary<Type, IFactory> GetGeneratedFactoriesMap(DatabaseConnection {databaseConnectionVariableName}) => new Dictionary<Type, IFactory>()"
        );
        sb.AppendLine("    {");
        if (factories.Length == 0) sb.AppendLine("        // No factories found");

        foreach (var f in factories.Where(x => x.GetType() == typeof(Factory)))
        {
            sb.AppendLine($"       {{ typeof({f.ModelTypeName.Name}), {f.InstanceCreation(databaseConnectionVariableName)} }},");
        }

        sb.AppendLine("    };");

        //mock
        sb.AppendLine(
            $"    private static partial Dictionary<Type, IFactory> GetGeneratedMockFactoriesMap() => new Dictionary<Type, IFactory>()"
        );
        sb.AppendLine("    {");
        if (factories.Length == 0) sb.AppendLine("        // No mock factories found");

        foreach (var f in factories.OfType<MockFactory>())
        {
            sb.AppendLine($"       {{ typeof({f.ModelTypeName.Name}), {f.InstanceCreation()} }},");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}