using System.Linq;
using Microsoft.CodeAnalysis;
using SzivarClubManager.SourceGenerator.Activities.Generation;
using SzivarClubManager.SourceGenerator.Activities.Target;

namespace SzivarClubManager.SourceGenerator.Activities;

[Generator]
public class Generator : IIncrementalGenerator
{
    private const string GeneratedOutputNamespace = "SzivarClubManager.SourceGeneration.Generated";


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var activities = Activity.GetCandidates(context);
        var pageActivities = PageActivity.GetCandidates(context);

        var combined = activities.Collect()
            .Combine(pageActivities.Collect());

        context.RegisterSourceOutput(combined, static (ctx, source) =>
        {
            var (activities, pageActivities) = source;

            ctx.AddSource(ActivityCollection.FileName, ActivityCollection.GenerateSource(activities.Concat(pageActivities)));
        });

        /*var targetCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                (ctx, _) => GetTarget(ctx)
            )
            .Where(t => t is not null)
            .Select((t, _) => t!);

        // Group and create activities for ActivityCollection
        context.RegisterSourceOutput(targetCandidates.Collect(), (ctx, activities) =>
        {
            var validActivities = activities
                // Replace Page Models to Page ViewModel
                .Select(x => x is PageActivityModel pam ? pam.ToPageActivity() : x)
                // Only keep Activities, only for type safety
                .OfType<Activity>()
                .ToImmutableArray();

            ctx.AddSource("ActivityCollection.g.cs", GenerateActivityCollection(validActivities));
        });*/
    }

    /*private static ITarget? GetTarget(GeneratorSyntaxContext context)
    {
        var pageActivityModel = PageActivityModel.IsTarget(context);
        if (pageActivityModel is not null) return pageActivityModel;

        var pageActivity = PageActivity.IsTarget(context);
        if (pageActivity is not null) return pageActivity;

        var activity = Activity.IsTarget(context);
        if (activity is not null) return activity;

        return null;
    }*/

    /*private static string GenerateActivityCollection(ImmutableArray<Activity> activities)
    {
        const string factoryProviderVariableName = "factoryProvider";

        var orderedActivities = activities
            .GroupBy(x => x.GetType().Name)
            .OrderBy(x => x.Key)
            .Select(x => x.OrderBy(a => a.DisplayName))
            .SelectMany(x => x);

        StringBuilder sb = new();
        sb.AppendLine("//<auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine("using SzivarClubManager.Datasources;");
        sb.AppendLine("using SzivarClubManager.ViewModels.Activities;");
        sb.AppendLine("using SzivarClubManager.ViewModels.Activities.Page.Wrapper;");
        sb.AppendLine();
        sb.AppendLine($"namespace {GeneratedOutputNamespace};");
        sb.AppendLine();
        sb.AppendLine("public static class ActivityCollection");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IReadOnlyDictionary<string, ActivityViewModel> GetActivities(FactoryProvider {factoryProviderVariableName}) => new Dictionary<string, ActivityViewModel>");
        sb.AppendLine("    {");
        if (activities.Length == 0) sb.AppendLine("        // No activities found");

        foreach (var a in orderedActivities)
        {
            if (a is PageActivity pa)
            {
                sb.AppendLine($"        {{ \"{a.DisplayName}\", {pa.InstanceCreation(factoryProviderVariableName)} }},");
            }
            else
            {
                sb.AppendLine($"        {{ \"{a.DisplayName}\", {a.InstanceCreation()} }},");
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }*/
}