using System.Collections.Generic;
using System.Linq;
using System.Text;
using SzivarClubManager.SourceGenerator.Generators.Activities.Target;

namespace SzivarClubManager.SourceGenerator.Generators.Activities.Generation;

public static class ActivityCollection
{
    public const string FileName = "ActivityCollection.g.cs";

    public static string GenerateSource(IEnumerable<Activity> activities)
    {
        const string activityVm = "global::SzivarClubManager.ViewModels.Activities.ActivityViewModel";
        const string factoryProvider = "global::SzivarClubManager.Datasources.FactoryProvider";
        const string readOnlyDict = $"global::System.Collections.Generic.IReadOnlyDictionary<string, {activityVm}>";
        const string dictionary = $"global::System.Collections.Generic.Dictionary<string, {activityVm}>";

        const string factoryProviderVarName = "factoryProvider";

        StringBuilder sb = new();

        sb.AppendLine("//<auto-generated />");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.SourceGeneration.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class ActivityCollection");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {readOnlyDict} GetActivities({factoryProvider} {factoryProviderVarName}) => new {dictionary}");
        sb.AppendLine("    {");

        foreach (var a in activities
                     .GroupBy(x => x.OrderGroup)
                     .OrderBy(x => x.Key)
                     .Select(x => x.OrderBy(a => a.DisplayName))
                     .SelectMany(x => x))
        {
            sb.AppendLine($"        {{ \"{a.DisplayName}\", {(a is PageActivity pa ? pa.InstanceCreation(factoryProviderVarName) : a.InstanceCreation())} }},");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}