using System.Collections.Generic;
using System.Text;
using SzivarClubManager.SourceGenerator.Pages.Target;

namespace SzivarClubManager.SourceGenerator.Pages.Generation;

public static class PageDataView
{
    public static string FileName => "PageDataView.g.cs";

    public static string GenerateSource(IEnumerable<PageDataViewModel> vms)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Avalonia.Controls;");
        sb.AppendLine("using SzivarClubManager.Models;");
        sb.AppendLine("using SzivarClubManager.ViewModels.Activities.Page.Data;");
        sb.AppendLine();
        sb.AppendLine("namespace SzivarClubManager.Views.Activities.Page.Data;");
        sb.AppendLine();
        sb.AppendLine("public abstract class PageDataView : UserControl");
        sb.AppendLine("{");
        sb.AppendLine("    protected void PageDataGrid_OnSelectionChanged(object? sender, SelectionChangedEventArgs e)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (sender is not DataGrid grid) return;");
        sb.AppendLine();
        sb.AppendLine("        switch (DataContext)");
        sb.AppendLine("        {");
        foreach (var vm in vms)
        {
            sb.AppendLine($"            case {vm.Name} vm:");
            sb.AppendLine($"                vm.SelectedItems = grid.SelectedItems.Cast<{vm.ModelName}>().ToArray();");
            sb.AppendLine("                break;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new ArgumentOutOfRangeException(nameof(DataContext));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");


        return sb.ToString();
    }
}